name: v1-arbitrageur-bot

plugins:
  - name: alchemy
    version: 0.7.1
  - name: etherscan
    version: 0.7.0
  - name: solidity
    version: 0.7.1
  - name: foundry
    version: 0.7.3

default_ecosystem: ethereum

ethereum:
  default_network: goerli
  mainnet_fork:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
      goerli:
        upstream_provider: alchemy

dependencies:
  - name: marginal-v1-periphery
    github: MarginalProtocol/v1-periphery
    ref: v1.0.0-beta.10
