name: v1-arbitrageur-bot

plugins:
  - name: alchemy
    version: 0.6.3
  - name: etherscan
    version: 0.6.11
  - name: solidity
    version: 0.6.9
  - name: foundry
    version: 0.6.12
  - name: arbitrum
    version: 0.6.1
  - name: base
    version: 0.6.3

default_ecosystem: ethereum

ethereum:
  default_network: base
  mainnet_fork:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
      goerli:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy
    base:
      mainnet:
        upstream_provider: alchemy

dependencies:
  - name: marginal-v1-periphery
    github: MarginalProtocol/v1-periphery
    ref: v1.0.0-beta.10
