name: v1-arbitrageur-bot

plugins:
  - name: alchemy
    version: 0.8.0
  - name: etherscan
    version: 0.8.0
  - name: solidity
    version: 0.8.2
  - name: foundry
    version: 0.8.0
  - name: arbitrum
    version: 0.8.0
  - name: base
    version: 0.8.0

default_ecosystem: ethereum

ethereum:
  default_network: ethereum
  mainnet_fork:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
      goerli:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy
    base:
      mainnet:
        upstream_provider: alchemy

dependencies:
  - name: marginal-v1-core
    github: MarginalProtocol/v1-core
    ref: v1.0.1
  - name: marginal-v1-periphery
    github: MarginalProtocol/v1-periphery
    ref: v1.0.1

solidity:
  via_ir: true
